### ISSUE TITLE
1.0 Development Roadmap

### ISSUE THREAD

**Issue by sidgames5** [sidgames5/voice-assistant#1]
Here is the full development roadmap for version 1.0:

- [x] Improve processing speeds
- [x] Improve question answering
- [x] Add text only mode
- [x] Add weather ability
