### ISSUE TITLE
1.1 Development Roadmap

### ISSUE THREAD

**Issue by sidgames5** [sidgames5/voice-assistant#3]
Here is the full development roadmap for version 1.1:

- [ ] #5
- [x] Add support for running ollama on a different server/computer
- [ ] #4
- [x] Add support for weather forecasts
- [x] Add support for internet searches
- [x] Allow for conversations and follow-up questions
- [x] Personalized experience
- [ ] #6
